### ISSUE TITLE
Add Content-Type Task/Todo

### ISSUE THREAD

**Issue by santonelli** [operun/operun.crm#15]
Tasks Schemata:

# Default
Title (mandatory, Text String)
Description (Text)

# Custom
ID (auto-generated, Integer)
Owner (Reference to User)
Start Date (Date)
End Date (Date)
Status (mandatory, Choice, Values are: New, Ongoing, Done)
Priority (mandatory, Choice, Values are: Low, Medium, High)

Use Plone's infrastructure to enable comments?

**Comment by Netroxen** [comment]
Priority 'Medium' should be 'Normal' as in Redmine, it's too explicit as a default value.

**Comment by Netroxen** [comment]
This feature along with other improvements has been added in the pull-request: https://github.com/operun/operun.crm/pull/60
